Repository exasol/postgresql-virtual-schema, pull requests merged in 2021-03, with the labels that each got.

#30 Added greenplum as supported source
  README.md
Labels: documentation

#29 doc/27: Added automatically generated capabilities report
  README.md
  doc/changes/changes_1.1.0.md
  doc/generated/capabilities.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/postgresql/docgeneration/CapabilitiesReport.java
  src/test/java/com/exasol/adapter/dialects/postgresql/docgeneration/PostgresAutogeneratedResourceVerifier.java
Labels: documentation

#33 #32: Remove SQL_DIALECT property
  doc/changes/changelog.md
  doc/changes/changes_1.1.0.md
  doc/changes/changes_2.0.0.md
  doc/dialects/postgresql.md
  pom.xml
  src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLColumnMetadataReader.java
  src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
  src/main/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLColumnMetadataReaderTest.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgresSQLSqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgresVirtualSchemaIntegrationTestSetup.java
  src/test/java/utils/SqlNodesCreator.java
Labels: refactoring

#36 #35: Fixed test that was using a hard coded host ip address
  doc/changes/changes_2.0.0.md
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgresVirtualSchemaIntegrationTestSetup.java
Labels: bug

#34 #17: Moved abstract scalar function test to virtual-schema-common-jdbc
  README.md
  doc/changes/changes_2.0.0.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLScalarFunctionsIT.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ExasolRun.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ScalarFunctionCallBuilder.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ScalarFunctionParameterFinder.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ScalarFunctionQueryBuilder.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ScalarFunctionsAbstractIT.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/ScalarFunctionsParameterCache.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/SingleRowSingleTableVirtualSchemaTestSetup.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/SingleTableVirtualSchemaTestSetup.java
  src/test/java/com/exasol/adapter/dialects/scalarfunction/VirtualSchemaRunVerifier.java
  src/test/resources/integration/scalarFunctionsParameterCache.yml
Labels: refactoring

#37 * #18: Fixed two integration tests
  doc/changes/changes_2.0.0.md
  src/test/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialectIT.java
Labels: refactoring
